services:
  termix:
    image: ghcr.io/lukegus/termix
    container_name: termix
    restart: unless-stopped
    volumes:
      - ${TERMIX_DATA_FOLDER:-./data}:/app/data
    environment:
      PORT: 8080
      GUACD_HOST: ${GUACD_IP}
    depends_on:
      - guacd
    networks:
      external:
        ipv4_address: ${TERMIX_IP}

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${GUACD_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}