services:
  termix:
    image: ghcr.io/lukegus/termix
    container_name: termix
    restart: unless-stopped
    volumes:
      - ${TERMIX_DATA_FOLDER:-./data}:/app/data
    environment:
      PORT: 8080
      GUACD_HOST: guacd
    depends_on:
      - guacd
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.2

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.3

networks:
  local:
    name: homarr-local-network
    ipam:
      config:
        - subnet: 172.${SUBNET_NUMBER:-20}.0.0/16