services:
  termix:
    image: ghcr.io/lukegus/termix
    container_name: termix
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      PORT: 8080
      GUACD_HOST: guacd
    depends_on:
      - guacd
    ports:
      - "${TERMIX_PORT:-8080}:8080"
    networks:
      net:

  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    networks:
      net:

networks:
  net:
    name: termix-local-network